controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

app_auction_new_recap:
    path: /auction/recap/{id}
    controller: App\Controller\AuctionController::newRecap
    methods: [GET]