<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXAOoLXz\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXAOoLXz/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXAOoLXz.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXAOoLXz\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXAOoLXz\App_KernelDevDebugContainer([
    'container.build_hash' => 'XAOoLXz',
    'container.build_id' => '29e623a9',
    'container.build_time' => 1689084584,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXAOoLXz');
