<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLSbkUST\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLSbkUST/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerLSbkUST.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerLSbkUST\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerLSbkUST\App_KernelDevDebugContainer([
    'container.build_hash' => 'LSbkUST',
    'container.build_id' => 'b8eb7d7f',
    'container.build_time' => 1689261450,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerLSbkUST');
