<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    'app_auction' => [[], ['_controller' => 'App\\Controller\\AuctionController::index'], [], [['text', '/auction/']], [], [], []],
    'app_auction_test' => [[], ['_controller' => 'App\\Controller\\AuctionController::test'], [], [['text', '/auction/test2']], [], [], []],
    'app_category' => [[], ['_controller' => 'App\\Controller\\CategoryController::category'], [], [['text', '/category/']], [], [], []],
    'app_subcategory' => [[], ['_controller' => 'App\\Controller\\CategoryController::subCategory'], [], [['text', '/category/subcategory']], [], [], []],
    'app_home' => [[], ['_controller' => 'App\\Controller\\HomeController::index'], [], [['text', '/home']], [], [], []],
    'app_register' => [[], ['_controller' => 'App\\Controller\\RegistrationController::register'], [], [['text', '/register']], [], [], []],
    'app_verify_email' => [[], ['_controller' => 'App\\Controller\\RegistrationController::verifyUserEmail'], [], [['text', '/verify/email']], [], [], []],
    'app_login' => [[], ['_controller' => 'App\\Controller\\SecurityController::login'], [], [['text', '/login']], [], [], []],
    'app_logout' => [[], ['_controller' => 'App\\Controller\\SecurityController::logout'], [], [['text', '/logout']], [], [], []],
    'app_user' => [[], ['_controller' => 'App\\Controller\\UserController::index'], [], [['text', '/user/']], [], [], []],
    'app_user_edit' => [[], ['_controller' => 'App\\Controller\\UserController::edit'], [], [['text', '/user/edit']], [], [], []],
    'app_user_delete' => [[], ['_controller' => 'App\\Controller\\UserController::delete'], [], [['text', '/user/delete']], [], [], []],
];
